blank_issues_enabled: true
contact_links:
  - name: ml5.js Discord Server
    url: https://discord.gg/FRc2SDyfKN
    about: For question like "How to fix this in my coding?", Please ask it on our Discord server.
  - name: ml5.js next-gen repo
    url: https://github.com/ml5js/ml5-next-gen/issues
    about: For issue related to the codebase, please create issue in this repo. 
